### ISSUE TITLE
Not Working on MacOS Sierra 10.12.6 | dlopen(libusb-1.0.dylib, 6): image not found

### ISSUE THREAD

**Issue by chelinho139** [vpelletier/python-libusb1#30]
Hello I am running MacOS Sierra 10.12.6
installed both ways using pip and also downloading source, neither way works.

Error:
`>>> import usb1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "usb1/__init__.py", line 61, in <module>
    from . import libusb1
  File "usb1/libusb1.py", line 199, in <module>
    libusb = _loadLibrary()
  File "usb1/libusb1.py", line 173, in _loadLibrary
    return dll_loader('libusb-1.0' + suffix, **loader_kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libusb-1.0.dylib, 6): image not found`

Any suggestions? Thanks in advance

**Comment by chelinho139** [comment]
finally did this:

brew rm libusb --force
brew install libusb


cheers!
