### ISSUE TITLE
Errors on Windows

### ISSUE THREAD

**Issue by demonguy** [vpelletier/python-libusb1#97]
I tried to use this library to access android devices via python script. So far I can:

1. my script works on Ubuntu and Mac
2. on Windows, my driver and device works fine with native Android `adb` tool
3. zadig shows my device driver is `WinUSB`
5. And I got errors below

Did I miss anything?

```
Looking for adb devices ...
Traceback (most recent call last):
  File "C:\Users\cy_ss_000.CY\miTrace\miTrace.py", line 146, in <module>
    devs = init_devices()
  File "C:\Users\cy_ss_000.CY\miTrace\miTrace.py", line 46, in init_devices
    dev.connect()
  File "C:\Users\cy_ss_000.CY\miTrace\lib/adb_shell\adb_shell\adb_device.py", line 675, in connect
    self._available, self._maxdata = self._io_manager.connect(self._banner, rsa_keys, auth_timeout_s, auth_callback, adb_info)
  File "C:\Users\cy_ss_000.CY\miTrace\lib/adb_shell\adb_shell\adb_device.py", line 221, in connect
    self._transport.connect(adb_info.transport_timeout_s)
  File "C:\Users\cy_ss_000.CY\miTrace\lib/adb_shell\adb_shell\transport\usb_transport.py", line 238, in connect
    transport = self._device.open()
  File "C:\Users\cy_ss_000.CY\AppData\Local\Programs\Python\Python39\lib\site-packages\usb1\__init__.py", line 2055, in open
    mayRaiseUSBError(libusb1.libusb_open(self.device_p, byref(handle)))
  File "C:\Users\cy_ss_000.CY\AppData\Local\Programs\Python\Python39\lib\site-packages\usb1\__init__.py", line 127, in mayRaiseUSBError
    __raiseUSBError(value)
  File "C:\Users\cy_ss_000.CY\AppData\Local\Programs\Python\Python39\lib\site-packages\usb1\__init__.py", line 119, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorAccess: LIBUSB_ERROR_ACCESS [-3]
```

![image](https://github.com/vpelletier/python-libusb1/assets/1451096/68a6b472-bcd0-4015-aea8-7f852b205dae)

**Comment by vpelletier** [comment]
As this is an error reported by `libusb_open` (so the C library directly), the first level of explanation I can give comes from [the libusb1 documentation for `libusb_open`](https://libusb.sourceforge.io/api-1.0/group__libusb__dev.html#ga3f184a8be4488a767b2e0ae07e76d1b0).

Then, the question becomes: Why does your windows user somehow not have the permission to open that device ?

My first thought was `libusb_detach_kernel_driver` (exposed as `DeviceHandle.detachKernelDriver` in this module), especially as you mention ADB may be installed on that system (and could hence somehow maybe take precedence over WinUSB ? I'm not sure), but the [libusb1 documentation states it is not available on windows](https://libusb.sourceforge.io/api-1.0/group__libusb__dev.html#ga5e0cc1d666097e915748593effdc634a).

Searching a bit, I find https://github.com/libusb/libusb/issues/1300 which suggests to me the 32bits library (and hence main executable ?) may somehow not be allowed to open devices running on a 64bits machine. What bit-width the python interpreter you are using is compiled for ?

**Comment by vpelletier** [comment]
Another approach to this question: here are two projects which implement the adb command in python, and both happen to use my module to access the USB bus:

https://github.com/google/python-adb (archived)

https://github.com/JeffLIrion/adb_shell (active)

**Comment by vpelletier** [comment]
Closing issue for lack of feedback.
